version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "[dependabot] npm:"
      
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[dependabot] composer:"
  
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/"  # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[dependabot] github actions:"